//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class gider
    {
        public int Id { get; set; }
        public string giderTuru { get; set; }
        public Nullable<double> tutar { get; set; }
    }
}
