//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class izin
    {
        public int Id { get; set; }
        public string tckNo { get; set; }
        public string gidecegiAdres { get; set; }
        public Nullable<System.DateTime> gidisTarihi { get; set; }
        public Nullable<System.DateTime> donusTarihi { get; set; }
        public string gidecegiKisiTel { get; set; }
    }
}
