//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class veritabanı : DbContext
    {
        public veritabanı()
            : base("name=veritabanı")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<izin> izin { get; set; }
        public virtual DbSet<odalar> odalar { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<odemeler> odemeler { get; set; }
        public virtual DbSet<menuler> menuler { get; set; }
        public virtual DbSet<gider> gider { get; set; }
    }
}
