//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class odemeler
    {
        public int Id { get; set; }
        public string tckNo { get; set; }
        public Nullable<int> vade { get; set; }
        public Nullable<int> kalanTaksit { get; set; }
        public Nullable<double> aylikTutar { get; set; }
        public Nullable<System.DateTime> odemeTarihi { get; set; }
    }
}
