//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public int Id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string tckNo { get; set; }
        public string okul { get; set; }
        public string bolum { get; set; }
        public Nullable<int> sinif { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
        public Nullable<int> sozlesmeSuresi { get; set; }
        public Nullable<int> kalacagiOda { get; set; }
        public string telefon { get; set; }
        public string veliAdi { get; set; }
        public string veliTelefon { get; set; }
        public string kanGrubu { get; set; }
        public string adresi { get; set; }
        public Nullable<int> odemelerBilgisi { get; set; }
        public string fotograf { get; set; }
    }
}
