//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public int Id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<double> maas { get; set; }
        public string gorevi { get; set; }
        public string fotograf { get; set; }
        public string kanGrubu { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string tckNo { get; set; }
    }
}
